const CONSTANTS = {
  PERMISSIONS: {
    COGNITO: {
      ADMIN: 'IM_ADMIN',
      USERS: 'Users',
      CUSTOMER: 'Customer',
    },
  },
  COMPONENTS: {
    TABLE: {
      ALL_TABLE_SIZE: 'All',
    },
  },

  DASHBOARD: {
    DRAWER_OPTIONS: {
      ACCESS_CONTROL: 'Access Control',
      PROCESS_RUNNER: 'Process Runner',
      WELCOME: 'Welcome',
      CUSTOMER_PREFERENCES: 'Customer Preferences',
    },
  },
  ENVIRONMENT: {
    DEVELOPMENT: 'development',
    PRODUCTION: 'production',
    STAGING: 'staging',
    VARIABLES: {
      AWS_USER_POOL_ID: 'REACT_APP_AWS_USER_POOL_ID',
      AWS_USER_POOL_WEB_CLIENT_ID: 'REACT_APP_AWS_USER_POOL_WEB_CLIENT_ID',
      AWS_REGION: 'REACT_APP_AWS_REGION',
      AWS_IDENTITY_POOL_ID: 'REACT_APP_AWS_IDENTITY_POOL_ID',
      POST_HOG_KEY: 'REACT_APP_POST_HOG_KEY',
    },
  },
  HTTP_RESPONSE_ERRORS: {
    EXPIRED_TOKEN: 'TokenExpiredError',
    COGNITO_NOT_AUTHORIZED: 'NotAuthorizedException',
  },
  HTTP_STATUS: {
    UNAUTHORIZED: 401,
  },
  EVENTS: {
    RENEW_SESSION: 'RENEW_SESSION',
  },
  QUERIES: {
    COGNITO_LIST_USERS: 'COGNITO_LIST_USERS',
    COGNITO_LIST_GROUPS: 'COGNITO_LIST_GROUPS',
    COGNITO_USERS_IN_GROUP: 'COGNITO_USERS_IN_GROUP',
    COGNITO_LIST_GROUPS_FOR_USER: 'COGNITO_LIST_GROUPS_FOR_USER',
    LIST_CUSTOMERS: 'LIST_CUSTOMERS',
    LIST_COUNTIES_FOR_CUSTOMER: 'LIST_COUNTIES_FOR_CUSTOMER',
    CUSTOMER_PREFERENCE_FOR_COUNTY: 'CUSTOMER_PREFERENCE_FOR_COUNTY',
    GET_DEFAULT_PRIORITIES_FOR_PROPERTY: 'GET_DEFAULT_PRIORITIES_FOR_PROPERTY',
    LIST_ENTREGAS: 'LIST_ENTREGAS',
    LIST_VENDAS: 'LIST_VENDAS',
    LIST_TICKETS: 'LIST_TICKETS',
  },
  STORAGE: {
    INITIALS: {
      COGNITO: 'Cognito',
      IM_APPLICATION: 'IM_APPLICATION',
    },
    KEYS: {
      IM_APPLICATION_AWS_COGNITO_USER: 'IM_APPLICATION_AWS_COGNITO_USER',
      IM_APPLICATION_AWS_COGNITO_EMAIL: 'IM_APPLICATION_AWS_COGNITO_EMAIL',
      IM_APPLICATION_JWT: 'IM_APPLICATION_JWT',
    },
  },
  GOOGLE_ICONS: {
    ADD: 'add',
    ARROW_FORWARD_IOS: 'arrow_forward_ios',
    ARROW_BACK_IOS: 'arrow_back_ios',
    CANCEL: 'cancel',
    CHECK: 'check',
    CHECK_CIRCLE: 'check_circle',
    CHECKLIST: 'checklist',
    CLOSE: 'close',
    DASHBOARD: 'dashboard',
    DELETE: 'delete',
    DESCRIPTION: 'description',
    DONE: 'done',
    EXPAND_LESS: 'expand_less',
    EXPAND_MORE: 'expand_more',
    MAIL: 'mail',
    FILTER_LIST: 'filter_list',
    FIRST_PAGE: 'first_page',
    FORM: 'edit_note',
    GEAR: 'settings',
    GRID: 'view_list',
    GROUP: 'group',
    INFO: 'info',
    KEYBOARD_ARROW_UP: 'keyboard_arrow_up',
    KEYBOARD_ARROW_DOWN: 'keyboard_arrow_down',
    KEYBOARD_RETURN: 'keyboard_return',
    LAST_PAGE: 'last_page',
    LOCK: 'lock',
    LOGIN: 'login',
    LOGOUT: 'logout',
    MANAGE_ACCOUNTS: 'manage_accounts',
    NAVIGATE_NEXT: 'navigate_next',
    REPLY: 'reply',
    NAVIGATE_BEFORE: 'navigate_before',
    PLAY_ARROW: 'play_arrow',
    SEARCH: 'search',
    SECURITY: 'security',
    SEND: 'send',
    SORT: 'sort',
    TABLE: 'table',
    UNDO: 'undo',
    VISIBILITY: 'visibility',
    VISIBILITY_OFF: 'visibility_off',
    WARNING: 'warning',
    SUPPORT_AGENT: 'support_agent',
  },
  TOAST_IDS: {
    RENEW_SESSION: 'RENEW_SESSION',
  },
  REGEX: {
    MIN_ONE_NUMBER: /.*\d.*$/g,
    MIN_ONE_UPPERCASE: /(?=.*[A-Z]).*$/g,
    MIN_ONE_SYMBOL_COGNITO_SUPPORT: /(?=.*[\^$*.[\]{}()?\-“!@#%&/,><’:;|_~`]).*$/g,
    MIN_ONE_LOWERCASE: /(?=.*[a-z]).*$/g,
    MIN_SIX_MAX_NINE_CHARACTERS: /(?=.{6,99}).*$/g,
  },
} as const;

export { CONSTANTS };
